const OPEN_FORM_PAGE = "OPEN_FORM_PAGE"
const OPEN_TABLE_PAGE = "OPEN_TABLE_PAGE"

const SAVE_FORM_DATA = "SAVE_FORM_DATA"
const RESET_FORM_HISTORY = "RESET_FORM_HISTORY"


export {OPEN_FORM_PAGE, OPEN_TABLE_PAGE,SAVE_FORM_DATA, RESET_FORM_HISTORY}