const OPEN_FORM_PAGE = "OPEN_FORM_PAGE"
const OPEN_TABLE_PAGE = "OPEN_TABLE_PAGE"

const SAVE_FORM_DATA = "SAVE_FORM_DATA"
const RESET_FORM_HISTORY = "RESET_FORM_HISTORY"

const NAME_VAL = "NAME_VAL"
const PHONE_VAL = "PHONE_VAL"
const EMAIL_VAL = "EMAIL_VAL"
const SERVICE_VAL= "SERVICE_VAL"
const BEVERAGE_VAL = "BEVERAGE_VAL"
const CLEANINESS_VAL = "CLEANINESS_VAL"
const OVERALL_VAL = "OVERALL_VAL"
const SET_VALUES_TO_DEFAULT = "SET_VALUES_TO_DEFAULT"


export {
        OPEN_FORM_PAGE, 
        OPEN_TABLE_PAGE,
        SAVE_FORM_DATA, 
        RESET_FORM_HISTORY,
        NAME_VAL, PHONE_VAL, 
        EMAIL_VAL, 
        SERVICE_VAL, 
        BEVERAGE_VAL,
        CLEANINESS_VAL, 
        OVERALL_VAL, 
        SET_VALUES_TO_DEFAULT }